### ISSUE TITLE
Adding a disclaimer to the project usage

### ISSUE THREAD

**Issue by aaronschweig** [DHBWMannheim/ml-server#3]
**Is your feature request related to a problem? Please describe.**
In german law there is a requirement that only financial institutions like banks, etc. are allowed to give "financial advise". This projects works with financial data and aims to provide a data foundation to describe the current market situation and guess a possible way in which a specific market can develop in a near future.

**Describe the solution you'd like**
To be on a safe path, it is required to find a battle proofed disclaimer, which ensures that this project doesn't provide any financial advise. Any suggestions from @jangruebener would be helpful, as he has some insight on the legal requirements.

**Describe alternatives you've considered**
None, because it is a legal requirement

**Additional context**

--

**Comment by jangruebener** [comment]
Hier mal ein Beispieltext, wie so ein Disclaimer aussehen kann:

> ### Disclaimer

> Alle Beiträge und Artikel auf dieser Seite wurden nach bestem Wissen und mit größtmöglicher Sorgfalt erstellt. Der Herausgeber übernimmt trotz sorgfältiger Überprüfung der zugrundeliegenden Quellen keine Gewähr für den Inhalt des Angebotes. Jede Haftung entstandener Schäden ist ausgeschlossen. Der Herausgeber haftet nicht für eingesandte Manuskripte und Unterlagen.

> Die hierin enthaltenen Angaben und Mitteilungen sind ausschließlich zur Information und zum persönlichen Gebrauch bestimmt. Keine der hierin enthaltenen Informationen begründet ein Angebot zum Verkauf oder die Werbung von Angeboten zum Kauf eines Terminkontraktes, eines Wertpapiers oder einer Option.

> Haftungsansprüche gegen den Herausgeber, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden, sind grundsätzlich ausgeschlossen, sofern seitens des Herausgebers kein nachweislich vorsätzliches Verschulden vorliegt.

> Alle Beiträge und Artikel auf dieser Seite stellen ausschließlich der Meinung des Herausgebers. Es findet keine Anlageberatung durch den Herausgeber oder die Entwickler des Projektes „Name“ statt. Dieser Beitrag ist eine journalistische Publikation und dient ausschließlich Informations- und Unterhaltungszwecken. Der Beitrag stellt keine Aufforderung zum Kauf oder Verkauf einer Aktie, eines Wertpapiers oder einer sonstigen Anlage dar. Jeder Anleger ist an dieser Stelle dazu aufgefordert, sich seine eigenen Gedanken zu machen, bevor eine Investitionsentscheidung trifft.

> Der Kauf von Aktien und anderen Wertpapieren ist mit hohen Risiken bis hin zum Totalverlust behaftet.

Prinzipiell sollten wir das Thema aber mal mit Michael absprechen und klären, wogegen er sich als Betreiber und Herausgeber absichern möchte. Grundsätzlich darf eine Finanz- und Anlageberatungen nur durch Banken vorgenommen werden. Daher müssen wir uns mit diesem Disclaimer absichern und kommunizieren, dass es sich bei dem Projekt nicht um eine Anlageberatung handelt!

**Comment by aaronschweig** [comment]
Danke @jangruebener für den ausführlichen Disclaimer! Denkst du, du könntest einen PR aufmachen, der den Disclaimer (evtl. auf Englisch) relativ prominent in der Readme platziert?
